
server:
  servlet:
    context-path: /api/v1

logging:
  file:
    name: inventory-merger.log

spring:
  h2:
    console:
      enabled: true
  task:
    scheduling:
      enabled: true
      thread-name-prefix: Product-Sync-
      product-sync-fixed-rate: 600000

feign:
  client:
    config:
      default:
           user-agent: curl/8.5.0
      providerA:
          url: https://fakestoreapi.com
      providerB:
          url: https://dummyjson.com
